[project]
name = "jobsearch-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apify-client~=1.11.0",
    "ollama>=0.5.1",
    "openai~=1.88.0",
    "pydantic~=2.11.7",
    "python-dotenv~=1.1.0",
]
